# Generated by Django 3.0.4 on 2020-03-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_fish', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fishing_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.PositiveIntegerField(default=0)),
                ('nuber_of_fish', models.PositiveIntegerField(default=0)),
                ('fish_weight', models.PositiveIntegerField(default=0)),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing')),
            ],
        ),
        migrations.CreateModel(
            name='Fish_Trophy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.PositiveIntegerField(default=0)),
                ('fish_trophy_weight', models.PositiveIntegerField(default=0)),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing')),
            ],
        ),
    ]
