# Generated by Django 3.0.4 on 2020-04-03 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overcast', models.CharField(max_length=30)),
                ('weather_locality', models.CharField(max_length=30)),
                ('weather_temperature', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('pressure', models.PositiveIntegerField(default=750)),
                ('direction_wind', models.CharField(max_length=30)),
                ('wind_speed', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('lunar_day', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather_Phenomena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_phenomena_name', models.CharField(max_length=20)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Weather')),
            ],
        ),
    ]
