# Generated by Django 3.0.4 on 2020-05-24 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingCrochet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crochet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fishing.Crochet', verbose_name='Крючок')),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fishing.Fishing', verbose_name='Рыбалка')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['crochet'],
            },
        ),
    ]
