# Generated by Django 3.0.4 on 2020-04-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishing_montage',
            name='fishing_montage_sliding',
            field=models.BooleanField(default=False, verbose_name='Скользящий монтаж'),
        ),
        migrations.AlterField(
            model_name='fishing_point',
            name='fishing_poiny_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_locality',
            field=models.CharField(max_length=50, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='point',
            name='point_depth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Глубина'),
        ),
    ]
