# Generated by Django 3.0.4 on 2020-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='name_of_fish',
            field=models.CharField(max_length=20, unique=True, verbose_name='Рыба'),
        ),
    ]
