# Generated by Django 3.0.4 on 2020-04-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_weather_weather_phenomena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aroma_manufacturer', models.CharField(max_length=100)),
                ('aroma_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bottom_Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottom_map_northern_degree', models.IntegerField(default=0)),
                ('bottom_map_northern_minute', models.IntegerField(default=0)),
                ('bottom_map_northern_second', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('bottom_map_easter_degree', models.IntegerField(default=0)),
                ('bottom_map_easter_minute', models.IntegerField(default=0)),
                ('bottom_map_easter_second', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lure_manufacturer', models.CharField(max_length=100)),
                ('lure_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bait', models.BooleanField(default=False)),
                ('nozzle_manufacturer', models.CharField(max_length=100)),
                ('nozzle_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Priming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priming_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.District')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_azimuth', models.PositiveIntegerField(default=0)),
                ('point_distance', models.PositiveIntegerField(default=0)),
                ('point_depth', models.PositiveIntegerField(default=0)),
                ('priming', models.PositiveIntegerField()),
                ('bottom_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Bottom_Map')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_locality', models.CharField(max_length=50)),
                ('bottom_map', models.PositiveIntegerField()),
                ('fishing_point', models.PositiveIntegerField()),
                ('place_northern_degree', models.IntegerField(default=0)),
                ('place_northern_minute', models.IntegerField(default=0)),
                ('place_northern_second', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('place_easter_degree', models.IntegerField(default=0)),
                ('place_easter_minute', models.IntegerField(default=0)),
                ('place_easter_second', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.District')),
                ('water', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Water')),
            ],
        ),
        migrations.CreateModel(
            name='Fishing_Tackle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishing_tackle_name', models.CharField(max_length=30)),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing')),
            ],
        ),
        migrations.CreateModel(
            name='Fishing_Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishing_point_azimuth', models.PositiveIntegerField(default=0)),
                ('fishing_point_distance', models.PositiveIntegerField(default=0)),
                ('fishing_poiny_depth', models.PositiveIntegerField(default=0)),
                ('priming', models.PositiveIntegerField()),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fishing')),
            ],
        ),
        migrations.AddField(
            model_name='bottom_map',
            name='water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Water'),
        ),
    ]
