# Generated by Django 3.0.4 on 2020-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20200414_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishing',
            name='date',
            field=models.DateField(verbose_name='Дата рыбалки'),
        ),
        migrations.AlterField(
            model_name='fishing',
            name='time',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='fishing_result',
            name='fish_weight',
            field=models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Вес улова'),
        ),
    ]
