# Generated by Django 3.0.4 on 2020-04-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20200419_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='modeltroughname',
            name='model_trough_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Модель кормушки'),
        ),
        migrations.AlterField(
            model_name='nozzlestate',
            name='state',
            field=models.CharField(max_length=20, unique=True, verbose_name='Состояние наживки'),
        ),
    ]
