# Generated by Django 3.0.4 on 2020-05-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fishing', '0002_fishingcrochet'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingNozzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fishing.Fishing', verbose_name='Рыбалка')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fishing.Nozzle', verbose_name='Наживка')),
                ('nozzle_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fishing.NozzleState', verbose_name='Состояние наживки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Владелец записи')),
            ],
            options={
                'verbose_name': 'Наживка использованная в рыбалке',
                'verbose_name_plural': 'Наживки использованная в рыбалке',
                'ordering': ['id'],
            },
        ),
    ]
