# Generated by Django 3.0.4 on 2020-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0003_auto_20200414_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ['name_of_fish'], 'verbose_name': 'Рыба', 'verbose_name_plural': 'Рыбы'},
        ),
        migrations.AlterModelOptions(
            name='overcast',
            options={'ordering': ['overcast_name'], 'verbose_name': 'Облачность', 'verbose_name_plural': 'Облачность'},
        ),
        migrations.RenameField(
            model_name='fishing_result',
            old_name='nuber_of_fish',
            new_name='number_of_fish',
        ),
        migrations.AlterField(
            model_name='place',
            name='place_locality',
            field=models.CharField(help_text='Название ближайшего населенного пункта', max_length=50, verbose_name='Населенный пункт'),
        ),
    ]
