# Generated by Django 3.0.4 on 2020-04-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_auto_20200416_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish_trophy',
            name='fish_trophy_weight',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Вес трофея'),
        ),
    ]
