# Generated by Django 3.0.4 on 2020-04-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0004_auto_20200405_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishing',
            name='name_fishing',
            field=models.CharField(default=0, max_length=30, verbose_name='Рыбалка'),
        ),
    ]
