# Generated by Django 3.0.4 on 2020-04-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0005_fishing_name_fishing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish_trophy',
            name='fish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fishing.Fish', verbose_name='Рыба'),
        ),
    ]
